---
spec/spec_helper_acceptance.rb:
  module_name: archlinux_workstation
.travis.yml:
  script: "\"bundle exec rake validate lint spec SPEC_OPTS='--format documentation'\""
  includes:
  - rvm: 2.2.5
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.3
    env: PUPPET_GEM_VERSION="~> 4.0"
